export const berryEntries = [
  {
    key: 'berry',
    endpoint: 'berry',
    cluster: 'berries',
    label: 'Berry',
    pluralLabel: 'Berries',
    icon: 'mdi:fruit-cherries',
    color: 'type-grass',
    description: 'Berries used for cooking, held items and Pokéblocks.',
    searchable: true,
    listFields: [
      { key: 'name', label: 'Name', kind: 'text', showInList: true },
      { key: 'growth_time', label: 'Growth Time', kind: 'number', showInList: true },
    ],
    detailFields: [
      { key: 'firmness', label: 'Firmness', kind: 'link', linkResourceType: 'berry-firmness', showInDetail: true },
      {
        key: 'flavors',
        label: 'Flavors',
        kind: 'badge-list',
        linkResourceType: 'berry-flavor',
        showInDetail: true,
        transform: (r) => r.flavors.map((f) => f.flavor),
      },
      { key: 'natural_gift_type', label: 'Natural Gift Type', kind: 'badge', linkResourceType: 'type', showInDetail: true },
      { key: 'natural_gift_power', label: 'Natural Gift Power', kind: 'number', showInDetail: true },
      { key: 'size', label: 'Size (mm)', kind: 'number', showInDetail: true },
      { key: 'max_harvest', label: 'Max Harvest', kind: 'number', showInDetail: true },
      { key: 'smoothness', label: 'Smoothness', kind: 'number', showInDetail: true },
      { key: 'soil_dryness', label: 'Soil Dryness', kind: 'number', showInDetail: true },
      { key: 'item', label: 'Corresponding Item', kind: 'link', linkResourceType: 'item', showInDetail: true },
    ],
  },
  {
    key: 'berry-firmness',
    endpoint: 'berry-firmness',
    cluster: 'berries',
    label: 'Berry Firmness',
    pluralLabel: 'Berry Firmnesses',
    icon: 'mdi:texture-box',
    color: 'type-grass',
    description: 'How firm a berry is — from very soft to super hard.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'berries', label: 'Berries', kind: 'link-list', linkResourceType: 'berry', showInDetail: true },
    ],
  },
  {
    key: 'berry-flavor',
    endpoint: 'berry-flavor',
    cluster: 'berries',
    label: 'Berry Flavor',
    pluralLabel: 'Berry Flavors',
    icon: 'mdi:noodles',
    color: 'type-grass',
    description: 'Spicy, dry, sweet, bitter and sour flavor profiles.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'contest_type', label: 'Contest Type', kind: 'link', linkResourceType: 'contest-type', showInDetail: true },
      {
        key: 'berries',
        label: 'Berries',
        kind: 'link-list',
        linkResourceType: 'berry',
        showInDetail: true,
        transform: (r) => r.berries.map((b) => b.berry),
      },
    ],
  },
]
