export const contestEntries = [
  {
    key: 'contest-type',
    endpoint: 'contest-type',
    cluster: 'contests',
    label: 'Contest Type',
    pluralLabel: 'Contest Types',
    icon: 'mdi:trophy-award',
    color: 'type-fairy',
    description: 'Cool, beautiful, cute, clever and tough contest categories.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'berry_flavor', label: 'Berry Flavor', kind: 'link', linkResourceType: 'berry-flavor', showInDetail: true },
    ],
  },
  {
    key: 'contest-effect',
    endpoint: 'contest-effect',
    cluster: 'contests',
    label: 'Contest Effect',
    pluralLabel: 'Contest Effects',
    icon: 'mdi:star-shooting',
    color: 'type-fairy',
    description: 'Appeal and jam values a move has in a Pokémon contest.',
    primaryIdentifier: 'id',
    listFields: [
      { key: 'id', label: 'ID', kind: 'text', showInList: true },
      { key: 'appeal', label: 'Appeal', kind: 'number', showInList: true },
      { key: 'jam', label: 'Jam', kind: 'number', showInList: true },
    ],
    detailFields: [
      { key: 'appeal', label: 'Appeal', kind: 'number', showInDetail: true },
      { key: 'jam', label: 'Jam', kind: 'number', showInDetail: true },
      { key: 'effect_entries', label: 'Effect', kind: 'localized-text', showInDetail: true },
      { key: 'flavor_text_entries', label: 'Flavor Text', kind: 'localized-text', showInDetail: true },
    ],
  },
  {
    key: 'super-contest-effect',
    endpoint: 'super-contest-effect',
    cluster: 'contests',
    label: 'Super Contest Effect',
    pluralLabel: 'Super Contest Effects',
    icon: 'mdi:star-four-points',
    color: 'type-fairy',
    description: 'Appeal values and the moves that share a Super Contest effect.',
    primaryIdentifier: 'id',
    listFields: [
      { key: 'id', label: 'ID', kind: 'text', showInList: true },
      { key: 'appeal', label: 'Appeal', kind: 'number', showInList: true },
    ],
    detailFields: [
      { key: 'appeal', label: 'Appeal', kind: 'number', showInDetail: true },
      { key: 'flavor_text_entries', label: 'Flavor Text', kind: 'localized-text', showInDetail: true },
      { key: 'moves', label: 'Moves', kind: 'link-list', linkResourceType: 'move', showInDetail: true },
    ],
  },
]
