export const gameEntries = [
  {
    key: 'generation',
    endpoint: 'generation',
    cluster: 'games',
    label: 'Generation',
    pluralLabel: 'Generations',
    icon: 'mdi:numeric',
    color: 'poke-blue',
    description: 'A generation of core-series Pokémon games.',
    searchable: true,
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'main_region', label: 'Main Region', kind: 'link', linkResourceType: 'region', showInDetail: true },
      { key: 'version_groups', label: 'Version Groups', kind: 'link-list', linkResourceType: 'version-group', showInDetail: true },
      { key: 'types', label: 'Types Introduced', kind: 'badge-list', linkResourceType: 'type', showInDetail: true },
      { key: 'abilities', label: 'Abilities Introduced', kind: 'link-list', linkResourceType: 'ability', showInDetail: true },
      { key: 'moves', label: 'Moves Introduced', kind: 'link-list', linkResourceType: 'move', showInDetail: true },
      { key: 'pokemon_species', label: 'Species Introduced', kind: 'link-list', linkResourceType: 'pokemon-species', showInDetail: true },
    ],
  },
  {
    key: 'pokedex',
    endpoint: 'pokedex',
    cluster: 'games',
    label: 'Pokédex',
    pluralLabel: 'Pokédexes',
    icon: 'mdi:book-open-page-variant',
    color: 'poke-blue',
    description: 'A regional or national listing of Pokémon species.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'is_main_series', label: 'Main Series', kind: 'boolean', showInDetail: true },
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'descriptions', label: 'Description', kind: 'localized-text', showInDetail: true },
      { key: 'region', label: 'Region', kind: 'link', linkResourceType: 'region', showInDetail: true },
      { key: 'version_groups', label: 'Version Groups', kind: 'link-list', linkResourceType: 'version-group', showInDetail: true },
      {
        key: 'pokemon_entries',
        label: 'Species',
        kind: 'link-list',
        linkResourceType: 'pokemon-species',
        showInDetail: true,
        transform: (r) => r.pokemon_entries.map((e) => e.pokemon_species),
      },
    ],
  },
  {
    key: 'version',
    endpoint: 'version',
    cluster: 'games',
    label: 'Version',
    pluralLabel: 'Versions',
    icon: 'mdi:disc-player',
    color: 'poke-blue',
    description: 'A specific game version, e.g. Red, Blue, Scarlet or Violet.',
    searchable: true,
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'version_group', label: 'Version Group', kind: 'link', linkResourceType: 'version-group', showInDetail: true },
    ],
  },
  {
    key: 'version-group',
    endpoint: 'version-group',
    cluster: 'games',
    label: 'Version Group',
    pluralLabel: 'Version Groups',
    icon: 'mdi:layers-triple',
    color: 'poke-blue',
    description: 'A group of game versions released together, e.g. Sword/Shield.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'order', label: 'Order', kind: 'number', showInDetail: true },
      { key: 'generation', label: 'Generation', kind: 'link', linkResourceType: 'generation', showInDetail: true },
      { key: 'versions', label: 'Versions', kind: 'link-list', linkResourceType: 'version', showInDetail: true },
      { key: 'regions', label: 'Regions', kind: 'link-list', linkResourceType: 'region', showInDetail: true },
      { key: 'pokedexes', label: 'Pokédexes', kind: 'link-list', linkResourceType: 'pokedex', showInDetail: true },
      { key: 'move_learn_methods', label: 'Move Learn Methods', kind: 'link-list', linkResourceType: 'move-learn-method', showInDetail: true },
    ],
  },
]
