export const itemEntries = [
  {
    key: 'item',
    endpoint: 'item',
    cluster: 'items',
    label: 'Item',
    pluralLabel: 'Items',
    icon: 'mdi:bag-personal',
    color: 'poke-gold',
    description: 'Held items, key items, medicine, balls and more.',
    searchable: true,
    listFields: [
      { key: 'sprites.default', label: '', kind: 'image', showInList: true },
      { key: 'name', label: 'Name', kind: 'text', showInList: true },
      { key: 'cost', label: 'Cost', kind: 'number', showInList: true },
    ],
    detailFields: [
      { key: 'sprites.default', label: 'Sprite', kind: 'image', showInDetail: true },
      { key: 'cost', label: 'Cost', kind: 'number', showInDetail: true },
      { key: 'fling_power', label: 'Fling Power', kind: 'number', showInDetail: true },
      { key: 'fling_effect', label: 'Fling Effect', kind: 'link', linkResourceType: 'item-fling-effect', showInDetail: true },
      { key: 'category', label: 'Category', kind: 'link', linkResourceType: 'item-category', showInDetail: true },
      { key: 'attributes', label: 'Attributes', kind: 'badge-list', linkResourceType: 'item-attribute', showInDetail: true },
      { key: 'effect_entries', label: 'Effect', kind: 'localized-text', showInDetail: true },
      { key: 'flavor_text_entries', label: 'Flavor Text', kind: 'localized-text', showInDetail: true },
      {
        key: 'held_by_pokemon',
        label: 'Held By',
        kind: 'link-list',
        linkResourceType: 'pokemon',
        showInDetail: true,
        transform: (r) => r.held_by_pokemon.map((h) => h.pokemon),
      },
    ],
  },
  {
    key: 'item-attribute',
    endpoint: 'item-attribute',
    cluster: 'items',
    label: 'Item Attribute',
    pluralLabel: 'Item Attributes',
    icon: 'mdi:tag-multiple',
    color: 'poke-gold',
    description: 'Traits an item can have, like "consumable" or "holdable".',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'descriptions', label: 'Description', kind: 'localized-text', showInDetail: true },
      { key: 'items', label: 'Items', kind: 'link-list', linkResourceType: 'item', showInDetail: true },
    ],
  },
  {
    key: 'item-category',
    endpoint: 'item-category',
    cluster: 'items',
    label: 'Item Category',
    pluralLabel: 'Item Categories',
    icon: 'mdi:shape',
    color: 'poke-gold',
    description: 'A grouping of items, e.g. "healing" or "evolution".',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'pocket', label: 'Pocket', kind: 'link', linkResourceType: 'item-pocket', showInDetail: true },
      { key: 'items', label: 'Items', kind: 'link-list', linkResourceType: 'item', showInDetail: true },
    ],
  },
  {
    key: 'item-fling-effect',
    endpoint: 'item-fling-effect',
    cluster: 'items',
    label: 'Item Fling Effect',
    pluralLabel: 'Item Fling Effects',
    icon: 'mdi:target',
    color: 'poke-gold',
    description: 'The extra effect that happens when an item is used with the move Fling.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'effect_entries', label: 'Effect', kind: 'localized-text', showInDetail: true },
      { key: 'items', label: 'Items', kind: 'link-list', linkResourceType: 'item', showInDetail: true },
    ],
  },
  {
    key: 'item-pocket',
    endpoint: 'item-pocket',
    cluster: 'items',
    label: 'Item Pocket',
    pluralLabel: 'Item Pockets',
    icon: 'mdi:archive',
    color: 'poke-gold',
    description: 'A section of the in-game bag, e.g. "berries" or "key items".',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'categories', label: 'Categories', kind: 'link-list', linkResourceType: 'item-category', showInDetail: true },
    ],
  },
]
