export const locationEntries = [
  {
    key: 'location',
    endpoint: 'location',
    cluster: 'locations',
    label: 'Location',
    pluralLabel: 'Locations',
    icon: 'mdi:map-marker',
    color: 'type-ground',
    description: 'A place within a region, made up of one or more areas.',
    searchable: true,
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'region', label: 'Region', kind: 'link', linkResourceType: 'region', showInDetail: true },
      { key: 'areas', label: 'Areas', kind: 'link-list', linkResourceType: 'location-area', showInDetail: true },
    ],
  },
  {
    key: 'location-area',
    endpoint: 'location-area',
    cluster: 'locations',
    label: 'Location Area',
    pluralLabel: 'Location Areas',
    icon: 'mdi:map-marker-radius',
    color: 'type-ground',
    description: 'A sub-area of a location where wild Pokémon can be encountered.',
    listFields: [
      { key: 'name', label: 'Name', kind: 'text', showInList: true },
      { key: 'location', label: 'Location', kind: 'link', linkResourceType: 'location', showInList: true },
    ],
    detailFields: [],
    detailComponent: 'LocationAreaDetail',
  },
  {
    key: 'pal-park-area',
    endpoint: 'pal-park-area',
    cluster: 'locations',
    label: 'Pal Park Area',
    pluralLabel: 'Pal Park Areas',
    icon: 'mdi:pine-tree',
    color: 'type-ground',
    description: 'A field in Pal Park where transferred Pokémon can be caught.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      {
        key: 'pokemon_encounters',
        label: 'Pokémon Found Here',
        kind: 'link-list',
        linkResourceType: 'pokemon-species',
        showInDetail: true,
        transform: (r) => r.pokemon_encounters.map((e) => e.pokemon_species),
      },
    ],
  },
  {
    key: 'region',
    endpoint: 'region',
    cluster: 'locations',
    label: 'Region',
    pluralLabel: 'Regions',
    icon: 'mdi:earth',
    color: 'type-ground',
    description: 'A large area of the Pokémon world, like Kanto or Galar.',
    searchable: true,
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'main_generation', label: 'Main Generation', kind: 'link', linkResourceType: 'generation', showInDetail: true },
      { key: 'locations', label: 'Locations', kind: 'link-list', linkResourceType: 'location', showInDetail: true },
      { key: 'pokedexes', label: 'Pokédexes', kind: 'link-list', linkResourceType: 'pokedex', showInDetail: true },
      { key: 'version_groups', label: 'Version Groups', kind: 'link-list', linkResourceType: 'version-group', showInDetail: true },
    ],
  },
]
