export const miscEntries = [
  {
    key: 'ability',
    endpoint: 'ability',
    cluster: 'misc',
    label: 'Ability',
    pluralLabel: 'Abilities',
    icon: 'mdi:flash',
    color: 'type-psychic',
    description: 'Passive effects a Pokémon can have, like Intimidate or Levitate.',
    searchable: true,
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'generation', label: 'Generation', kind: 'link', linkResourceType: 'generation', showInDetail: true },
      { key: 'is_main_series', label: 'Main Series', kind: 'boolean', showInDetail: true },
      { key: 'effect_entries', label: 'Effect', kind: 'localized-text', showInDetail: true },
      { key: 'flavor_text_entries', label: 'Flavor Text', kind: 'localized-text', showInDetail: true },
      {
        key: 'pokemon',
        label: 'Pokémon With This Ability',
        kind: 'link-list',
        linkResourceType: 'pokemon',
        showInDetail: true,
        transform: (r) => r.pokemon.map((p) => p.pokemon),
      },
    ],
  },
  {
    key: 'characteristic',
    endpoint: 'characteristic',
    cluster: 'misc',
    label: 'Characteristic',
    pluralLabel: 'Characteristics',
    icon: 'mdi:comment-text',
    color: 'type-psychic',
    description: 'A flavor description hinting at a Pokémon’s highest individual value stat.',
    primaryIdentifier: 'id',
    listFields: [
      { key: 'id', label: 'ID', kind: 'text', showInList: true },
      { key: 'highest_stat', label: 'Highest Stat', kind: 'link', linkResourceType: 'stat', showInList: true },
    ],
    detailFields: [
      { key: 'gene_modulo', label: 'Gene Modulo', kind: 'number', showInDetail: true },
      { key: 'highest_stat', label: 'Highest Stat', kind: 'link', linkResourceType: 'stat', showInDetail: true },
      { key: 'descriptions', label: 'Description', kind: 'localized-text', showInDetail: true },
    ],
  },
  {
    key: 'egg-group',
    endpoint: 'egg-group',
    cluster: 'misc',
    label: 'Egg Group',
    pluralLabel: 'Egg Groups',
    icon: 'mdi:egg',
    color: 'type-psychic',
    description: 'Groups that determine which Pokémon can breed together.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'pokemon_species', label: 'Species', kind: 'link-list', linkResourceType: 'pokemon-species', showInDetail: true },
    ],
  },
  {
    key: 'gender',
    endpoint: 'gender',
    cluster: 'misc',
    label: 'Gender',
    pluralLabel: 'Genders',
    icon: 'mdi:gender-transgender',
    color: 'type-psychic',
    description: 'Male, female or genderless, and the species that share each rate.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      {
        key: 'pokemon_species_details',
        label: 'Species',
        kind: 'link-list',
        linkResourceType: 'pokemon-species',
        showInDetail: true,
        transform: (r) => r.pokemon_species_details.map((d) => d.pokemon_species),
      },
      { key: 'required_for_evolution', label: 'Required For Evolution', kind: 'link-list', linkResourceType: 'pokemon-species', showInDetail: true },
    ],
  },
  {
    key: 'growth-rate',
    endpoint: 'growth-rate',
    cluster: 'misc',
    label: 'Growth Rate',
    pluralLabel: 'Growth Rates',
    icon: 'mdi:chart-line',
    color: 'type-psychic',
    description: 'How quickly a Pokémon species levels up with experience.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'formula', label: 'Formula', kind: 'text', showInDetail: true },
      { key: 'descriptions', label: 'Description', kind: 'localized-text', showInDetail: true },
      { key: 'pokemon_species', label: 'Species', kind: 'link-list', linkResourceType: 'pokemon-species', showInDetail: true },
    ],
  },
  {
    key: 'nature',
    endpoint: 'nature',
    cluster: 'misc',
    label: 'Nature',
    pluralLabel: 'Natures',
    icon: 'mdi:emoticon-outline',
    color: 'type-psychic',
    description: 'A personality that boosts one stat and lowers another.',
    searchable: true,
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'increased_stat', label: 'Increased Stat', kind: 'badge', linkResourceType: 'stat', showInDetail: true },
      { key: 'decreased_stat', label: 'Decreased Stat', kind: 'badge', linkResourceType: 'stat', showInDetail: true },
      { key: 'likes_flavor', label: 'Likes Flavor', kind: 'link', linkResourceType: 'berry-flavor', showInDetail: true },
      { key: 'hates_flavor', label: 'Hates Flavor', kind: 'link', linkResourceType: 'berry-flavor', showInDetail: true },
    ],
  },
  {
    key: 'pokeathlon-stat',
    endpoint: 'pokeathlon-stat',
    cluster: 'misc',
    label: 'Pokéathlon Stat',
    pluralLabel: 'Pokéathlon Stats',
    icon: 'mdi:run-fast',
    color: 'type-psychic',
    description: 'A stat used in Pokéathlon events, like Speed or Stamina.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [{ key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true }],
  },
  {
    key: 'pokemon-color',
    endpoint: 'pokemon-color',
    cluster: 'misc',
    label: 'Pokémon Color',
    pluralLabel: 'Pokémon Colors',
    icon: 'mdi:palette',
    color: 'type-psychic',
    description: "The Pokédex's color categorization for a species.",
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'pokemon_species', label: 'Species', kind: 'link-list', linkResourceType: 'pokemon-species', showInDetail: true },
    ],
  },
  {
    key: 'pokemon-form',
    endpoint: 'pokemon-form',
    cluster: 'misc',
    label: 'Pokémon Form',
    pluralLabel: 'Pokémon Forms',
    icon: 'mdi:shape-outline',
    color: 'type-psychic',
    description: 'An alternate form of a Pokémon, e.g. regional or Mega forms.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'pokemon', label: 'Pokémon', kind: 'link', linkResourceType: 'pokemon', showInDetail: true },
      { key: 'is_default', label: 'Default Form', kind: 'boolean', showInDetail: true },
      { key: 'is_mega', label: 'Mega Evolution', kind: 'boolean', showInDetail: true },
      { key: 'is_battle_only', label: 'Battle Only', kind: 'boolean', showInDetail: true },
      { key: 'version_group', label: 'Version Group', kind: 'link', linkResourceType: 'version-group', showInDetail: true },
      {
        key: 'types',
        label: 'Types',
        kind: 'badge-list',
        linkResourceType: 'type',
        showInDetail: true,
        transform: (r) => r.types.map((t) => t.type),
      },
    ],
  },
  {
    key: 'pokemon-habitat',
    endpoint: 'pokemon-habitat',
    cluster: 'misc',
    label: 'Pokémon Habitat',
    pluralLabel: 'Pokémon Habitats',
    icon: 'mdi:pine-tree-box',
    color: 'type-psychic',
    description: 'Where a species is naturally found — cave, forest, sea and more.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'pokemon_species', label: 'Species', kind: 'link-list', linkResourceType: 'pokemon-species', showInDetail: true },
    ],
  },
  {
    key: 'pokemon-shape',
    endpoint: 'pokemon-shape',
    cluster: 'misc',
    label: 'Pokémon Shape',
    pluralLabel: 'Pokémon Shapes',
    icon: 'mdi:shape-polygon-plus',
    color: 'type-psychic',
    description: "A species' body shape, used for Pokédex sorting.",
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'pokemon_species', label: 'Species', kind: 'link-list', linkResourceType: 'pokemon-species', showInDetail: true },
    ],
  },
  {
    key: 'pokemon-species',
    endpoint: 'pokemon-species',
    cluster: 'misc',
    label: 'Pokémon Species',
    pluralLabel: 'Pokémon Species',
    icon: 'mdi:dna',
    color: 'type-psychic',
    description: 'Species-level data: flavor text, breeding, evolution and Pokédex info.',
    searchable: true,
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'genera', label: 'Genus', kind: 'localized-text', showInDetail: true },
      { key: 'flavor_text_entries', label: 'Flavor Text', kind: 'localized-text', showInDetail: true },
      { key: 'generation', label: 'Generation', kind: 'link', linkResourceType: 'generation', showInDetail: true },
      { key: 'color', label: 'Color', kind: 'badge', linkResourceType: 'pokemon-color', showInDetail: true },
      { key: 'shape', label: 'Shape', kind: 'link', linkResourceType: 'pokemon-shape', showInDetail: true },
      { key: 'habitat', label: 'Habitat', kind: 'link', linkResourceType: 'pokemon-habitat', showInDetail: true },
      { key: 'growth_rate', label: 'Growth Rate', kind: 'link', linkResourceType: 'growth-rate', showInDetail: true },
      { key: 'egg_groups', label: 'Egg Groups', kind: 'link-list', linkResourceType: 'egg-group', showInDetail: true },
      { key: 'is_legendary', label: 'Legendary', kind: 'boolean', showInDetail: true },
      { key: 'is_mythical', label: 'Mythical', kind: 'boolean', showInDetail: true },
      { key: 'is_baby', label: 'Baby', kind: 'boolean', showInDetail: true },
      { key: 'capture_rate', label: 'Capture Rate', kind: 'number', showInDetail: true },
      { key: 'base_happiness', label: 'Base Happiness', kind: 'number', showInDetail: true },
      { key: 'hatch_counter', label: 'Hatch Counter (steps)', kind: 'number', showInDetail: true },
      { key: 'evolves_from_species', label: 'Evolves From', kind: 'link', linkResourceType: 'pokemon-species', showInDetail: true },
      { key: 'evolution_chain', label: 'Evolution Chain', kind: 'link', linkResourceType: 'evolution-chain', showInDetail: true },
    ],
  },
  {
    key: 'stat',
    endpoint: 'stat',
    cluster: 'misc',
    label: 'Stat',
    pluralLabel: 'Stats',
    icon: 'mdi:chart-bar',
    color: 'type-psychic',
    description: 'The base stats used in battle — HP, Attack, Defense and more.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'is_battle_only', label: 'Battle Only', kind: 'boolean', showInDetail: true },
      { key: 'move_damage_class', label: 'Damage Class', kind: 'link', linkResourceType: 'move-damage-class', showInDetail: true },
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
    ],
  },
  {
    key: 'type',
    endpoint: 'type',
    cluster: 'misc',
    label: 'Type',
    pluralLabel: 'Types',
    icon: 'mdi:shield-star',
    color: 'type-dragon',
    description: 'The 18 elemental types and their strengths and weaknesses.',
    searchable: true,
    listFields: [{ key: 'name', label: 'Name', kind: 'badge', showInList: true }],
    detailFields: [
      { key: 'generation', label: 'Generation', kind: 'link', linkResourceType: 'generation', showInDetail: true },
      { key: 'move_damage_class', label: 'Damage Class', kind: 'link', linkResourceType: 'move-damage-class', showInDetail: true },
      { key: 'damage_relations.double_damage_to', label: 'Super Effective Against', kind: 'badge-list', linkResourceType: 'type', showInDetail: true },
      { key: 'damage_relations.half_damage_to', label: 'Not Very Effective Against', kind: 'badge-list', linkResourceType: 'type', showInDetail: true },
      { key: 'damage_relations.no_damage_to', label: 'No Effect Against', kind: 'badge-list', linkResourceType: 'type', showInDetail: true },
      { key: 'damage_relations.double_damage_from', label: 'Weak To', kind: 'badge-list', linkResourceType: 'type', showInDetail: true },
      { key: 'damage_relations.half_damage_from', label: 'Resistant To', kind: 'badge-list', linkResourceType: 'type', showInDetail: true },
      { key: 'damage_relations.no_damage_from', label: 'Immune To', kind: 'badge-list', linkResourceType: 'type', showInDetail: true },
      {
        key: 'pokemon',
        label: 'Pokémon',
        kind: 'link-list',
        linkResourceType: 'pokemon',
        showInDetail: true,
        transform: (r) => r.pokemon.map((p) => p.pokemon),
      },
    ],
  },
  {
    key: 'language',
    endpoint: 'language',
    cluster: 'misc',
    label: 'Language',
    pluralLabel: 'Languages',
    icon: 'mdi:translate',
    color: 'type-psychic',
    description: 'The languages PokeAPI provides localized names and text in.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'official', label: 'Official', kind: 'boolean', showInDetail: true },
      { key: 'iso639', label: 'ISO 639', kind: 'text', showInDetail: true },
      { key: 'iso3166', label: 'ISO 3166', kind: 'text', showInDetail: true },
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
    ],
  },
]
