export const moveEntries = [
  {
    key: 'move',
    endpoint: 'move',
    cluster: 'moves',
    label: 'Move',
    pluralLabel: 'Moves',
    icon: 'mdi:sword-cross',
    color: 'type-fighting',
    description: 'Every attack and status move a Pokémon can learn.',
    searchable: true,
    listFields: [
      { key: 'name', label: 'Name', kind: 'text', showInList: true },
      { key: 'type', label: 'Type', kind: 'badge', linkResourceType: 'type', showInList: true },
      { key: 'power', label: 'Power', kind: 'number', showInList: true },
    ],
    detailFields: [
      { key: 'type', label: 'Type', kind: 'badge', linkResourceType: 'type', showInDetail: true },
      { key: 'damage_class', label: 'Damage Class', kind: 'link', linkResourceType: 'move-damage-class', showInDetail: true },
      { key: 'power', label: 'Power', kind: 'number', showInDetail: true },
      { key: 'accuracy', label: 'Accuracy', kind: 'number', showInDetail: true },
      { key: 'pp', label: 'PP', kind: 'number', showInDetail: true },
      { key: 'priority', label: 'Priority', kind: 'number', showInDetail: true },
      { key: 'target', label: 'Target', kind: 'link', linkResourceType: 'move-target', showInDetail: true },
      { key: 'generation', label: 'Generation', kind: 'link', linkResourceType: 'generation', showInDetail: true },
      { key: 'contest_type', label: 'Contest Type', kind: 'link', linkResourceType: 'contest-type', showInDetail: true },
      {
        key: 'meta.ailment',
        label: 'Ailment',
        kind: 'link',
        linkResourceType: 'move-ailment',
        showInDetail: true,
      },
      { key: 'effect_entries', label: 'Effect', kind: 'localized-text', showInDetail: true },
      { key: 'flavor_text_entries', label: 'Flavor Text', kind: 'localized-text', showInDetail: true },
      { key: 'learned_by_pokemon', label: 'Learned By', kind: 'link-list', linkResourceType: 'pokemon', showInDetail: true },
    ],
  },
  {
    key: 'move-ailment',
    endpoint: 'move-ailment',
    cluster: 'moves',
    label: 'Move Ailment',
    pluralLabel: 'Move Ailments',
    icon: 'mdi:emoticon-sick',
    color: 'type-fighting',
    description: 'A status condition a move can inflict, like paralysis or poison.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true },
      { key: 'moves', label: 'Moves', kind: 'link-list', linkResourceType: 'move', showInDetail: true },
    ],
  },
  {
    key: 'move-battle-style',
    endpoint: 'move-battle-style',
    cluster: 'moves',
    label: 'Move Battle Style',
    pluralLabel: 'Move Battle Styles',
    icon: 'mdi:karate',
    color: 'type-fighting',
    description: 'A battle style used in Triple Battles, like "attack" or "defense".',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [{ key: 'names', label: 'Localized Name', kind: 'localized-name', showInDetail: true }],
  },
  {
    key: 'move-category',
    endpoint: 'move-category',
    cluster: 'moves',
    label: 'Move Category',
    pluralLabel: 'Move Categories',
    icon: 'mdi:format-list-bulleted-type',
    color: 'type-fighting',
    description: "A move's meta category, e.g. \"damage+lower\" or \"net-good-stats\".",
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'descriptions', label: 'Description', kind: 'localized-text', showInDetail: true },
      { key: 'moves', label: 'Moves', kind: 'link-list', linkResourceType: 'move', showInDetail: true },
    ],
  },
  {
    key: 'move-damage-class',
    endpoint: 'move-damage-class',
    cluster: 'moves',
    label: 'Move Damage Class',
    pluralLabel: 'Move Damage Classes',
    icon: 'mdi:fist-raised',
    color: 'type-fighting',
    description: 'Physical, special or status — how a move deals its damage.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'descriptions', label: 'Description', kind: 'localized-text', showInDetail: true },
      { key: 'moves', label: 'Moves', kind: 'link-list', linkResourceType: 'move', showInDetail: true },
    ],
  },
  {
    key: 'move-learn-method',
    endpoint: 'move-learn-method',
    cluster: 'moves',
    label: 'Move Learn Method',
    pluralLabel: 'Move Learn Methods',
    icon: 'mdi:school',
    color: 'type-fighting',
    description: 'How a Pokémon learns a move — level-up, TM, egg move, tutoring.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'descriptions', label: 'Description', kind: 'localized-text', showInDetail: true },
      { key: 'version_groups', label: 'Version Groups', kind: 'link-list', linkResourceType: 'version-group', showInDetail: true },
    ],
  },
  {
    key: 'move-target',
    endpoint: 'move-target',
    cluster: 'moves',
    label: 'Move Target',
    pluralLabel: 'Move Targets',
    icon: 'mdi:crosshairs-gps',
    color: 'type-fighting',
    description: 'Who a move can be aimed at — one target, all foes, the user, etc.',
    listFields: [{ key: 'name', label: 'Name', kind: 'text', showInList: true }],
    detailFields: [
      { key: 'descriptions', label: 'Description', kind: 'localized-text', showInDetail: true },
      { key: 'moves', label: 'Moves', kind: 'link-list', linkResourceType: 'move', showInDetail: true },
    ],
  },
]
